Implement workflow based on bbs+ repo
mesur-io/post-quantum-signatures pull request #5
Opened 2022-01-26 18:12 UTC by brownoxford

This is the first step required for the github workflow based on the `martinthomson/i-d-template` actions. Next will be to move the content of the spec into the skeleton draft document.

2022-01-26 18:13 UTC, brownoxford commented
This addresses #1

2022-01-26 22:16 UTC, mprorock approved these changes
approved, but I unfortunately created conflicts for you - will avoid that in the future

2022-01-27 14:24 UTC, mprorock requested changes
see notes around making sure links to github go to the mesur-io repo as well as readme title - otherwise i think good

2022-01-27 14:24 UTC, mprorock commented on README.md
> +# CRYSTALS-Dilithium JSON Encoding
this should be updated to JSON Encoding for Post Quantum Signatures

2022-01-27 14:24 UTC, mprorock commented on README.md
> +* [Editor's Copy](https://brownoxford.github.io/post-quantum-signatures/#go.draft-post-quantum-signatures.html)
this is pointing at `brownoxford` rather than `mesur-io` as are several other links out

2022-01-27 15:43 UTC, mprorock approved these changes

2022-01-27 15:43 UTC, merged